# Note: Follower counts are approximate representations of 2026 data.
# Organizational accounts (like Instagram, Nike, National Geographic) have been 
# filtered out to provide a list specifically of "famous persons."

famous_persons = [
    {"name": "Cristiano Ronaldo", "insta_follower_count": 673000000, "description": "Professional Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "insta_follower_count": 512000000, "description": "Professional Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "insta_follower_count": 415000000, "description": "Musician and Actress", "country": "United States"},
    {"name": "Kylie Jenner", "insta_follower_count": 391000000, "description": "Media Personality and Businesswoman", "country": "United States"},
    {"name": "Dwayne Johnson", "insta_follower_count": 390000000, "description": "Actor and Professional Wrestler", "country": "United States"},
    {"name": "Ariana Grande", "insta_follower_count": 372000000, "description": "Musician and Actress", "country": "United States"},
    {"name": "Kim Kardashian", "insta_follower_count": 353000000, "description": "Media Personality and Businesswoman", "country": "United States"},
    {"name": "Beyoncé", "insta_follower_count": 308000000, "description": "Musician", "country": "United States"},
    {"name": "Khloé Kardashian", "insta_follower_count": 299000000, "description": "Media Personality", "country": "United States"},
    {"name": "Justin Bieber", "insta_follower_count": 293000000, "description": "Musician", "country": "Canada"},
    {"name": "Kendall Jenner", "insta_follower_count": 285000000, "description": "Model and Media Personality", "country": "United States"},
    {"name": "Taylor Swift", "insta_follower_count": 281000000, "description": "Musician", "country": "United States"},
    {"name": "Virat Kohli", "insta_follower_count": 276000000, "description": "Cricketer", "country": "India"},
    {"name": "Jennifer Lopez", "insta_follower_count": 246000000, "description": "Musician and Actress", "country": "United States"},
    {"name": "Neymar Jr", "insta_follower_count": 235000000, "description": "Professional Footballer", "country": "Brazil"},
    {"name": "Nicki Minaj", "insta_follower_count": 224000000, "description": "Musician", "country": "Trinidad and Tobago"},
    {"name": "Kourtney Kardashian", "insta_follower_count": 215000000, "description": "Media Personality", "country": "United States"},
    {"name": "Miley Cyrus", "insta_follower_count": 211000000, "description": "Musician and Actress", "country": "United States"},
    {"name": "Katy Perry", "insta_follower_count": 201000000, "description": "Musician", "country": "United States"},
    {"name": "Zendaya", "insta_follower_count": 177000000, "description": "Actress and Singer", "country": "United States"},
    {"name": "Kevin Hart", "insta_follower_count": 176000000, "description": "Comedian and Actor", "country": "United States"},
    {"name": "Cardi B", "insta_follower_count": 164000000, "description": "Musician", "country": "United States"},
    {"name": "LeBron James", "insta_follower_count": 157000000, "description": "Basketball Player", "country": "United States"},
    {"name": "Demi Lovato", "insta_follower_count": 152000000, "description": "Musician and Actress", "country": "United States"},
    {"name": "Rihanna", "insta_follower_count": 149000000, "description": "Musician and Businesswoman", "country": "Barbados"},
    {"name": "Chris Brown", "insta_follower_count": 143000000, "description": "Musician", "country": "United States"},
    {"name": "Drake", "insta_follower_count": 142000000, "description": "Musician", "country": "Canada"},
    {"name": "Ellen DeGeneres", "insta_follower_count": 134000000, "description": "Comedian and Television Host", "country": "United States"},
    {"name": "Kylian Mbappé", "insta_follower_count": 131000000, "description": "Professional Footballer", "country": "France"},
    {"name": "Billie Eilish", "insta_follower_count": 125000000, "description": "Musician", "country": "United States"},
    {"name": "Lisa (Manobal)", "insta_follower_count": 107000000, "description": "Musician", "country": "Thailand"},
    {"name": "Gal Gadot", "insta_follower_count": 106000000, "description": "Actress", "country": "Israel"},
    {"name": "Vin Diesel", "insta_follower_count": 105000000, "description": "Actor", "country": "United States"},
    {"name": "Narendra Modi", "insta_follower_count": 101000000, "description": "Politician", "country": "India"},
    {"name": "Shakira", "insta_follower_count": 96000000, "description": "Musician", "country": "Colombia"},
    {"name": "Shraddha Kapoor", "insta_follower_count": 94000000, "description": "Actress", "country": "India"},
    {"name": "Priyanka Chopra", "insta_follower_count": 94000000, "description": "Actress", "country": "India"},
    {"name": "Jennie Kim", "insta_follower_count": 90000000, "description": "Musician", "country": "South Korea"},
    {"name": "Snoop Dogg", "insta_follower_count": 88000000, "description": "Musician", "country": "United States"},
    {"name": "Dua Lipa", "insta_follower_count": 88000000, "description": "Musician", "country": "United Kingdom"},
    {"name": "David Beckham", "insta_follower_count": 88000000, "description": "Former Professional Footballer", "country": "United Kingdom"},
    {"name": "Alia Bhatt", "insta_follower_count": 87000000, "description": "Actress", "country": "India"},
    {"name": "MrBeast", "insta_follower_count": 86000000, "description": "YouTuber", "country": "United States"},
    {"name": "Rosé (Park Chae-young)", "insta_follower_count": 84000000, "description": "Musician", "country": "South Korea"},
    {"name": "Jisoo", "insta_follower_count": 80000000, "description": "Musician", "country": "South Korea"},
    {"name": "Deepika Padukone", "insta_follower_count": 80000000, "description": "Actress", "country": "India"},
    {"name": "Katrina Kaif", "insta_follower_count": 80000000, "description": "Actress", "country": "India"},
    {"name": "Ronaldinho", "insta_follower_count": 79000000, "description": "Former Professional Footballer", "country": "Brazil"},
    {"name": "Neha Kakkar", "insta_follower_count": 78000000, "description": "Musician", "country": "India"},
    {"name": "Khaby Lame", "insta_follower_count": 77000000, "description": "Social Media Personality", "country": "Italy"},
    {"name": "Gigi Hadid", "insta_follower_count": 75000000, "description": "Model", "country": "United States"},
    {"name": "Karim Benzema", "insta_follower_count": 75000000, "description": "Professional Footballer", "country": "France"},
    {"name": "Salman Khan", "insta_follower_count": 72000000, "description": "Actor", "country": "India"},
    {"name": "V (Kim Taehyung)", "insta_follower_count": 72000000, "description": "Musician", "country": "South Korea"},
    {"name": "Emma Watson", "insta_follower_count": 72000000, "description": "Actress", "country": "United Kingdom"},
    {"name": "Georgina Rodríguez", "insta_follower_count": 72000000, "description": "Social Media Personality", "country": "Spain"},
    {"name": "Millie Bobby Brown", "insta_follower_count": 72000000, "description": "Actress", "country": "United Kingdom"},
    {"name": "Karol G", "insta_follower_count": 71000000, "description": "Musician", "country": "Colombia"},
    {"name": "Justin Timberlake", "insta_follower_count": 71000000, "description": "Musician and Actor", "country": "United States"},
    {"name": "Jacqueline Fernandez", "insta_follower_count": 70000000, "description": "Actress", "country": "Sri Lanka"},
    {"name": "Shawn Mendes", "insta_follower_count": 70000000, "description": "Musician", "country": "Canada"},
    {"name": "Urvashi Rautela", "insta_follower_count": 69000000, "description": "Actress and Model", "country": "India"},
    {"name": "Will Smith", "insta_follower_count": 69000000, "description": "Actor", "country": "United States"},
    {"name": "Anushka Sharma", "insta_follower_count": 68000000, "description": "Actress", "country": "India"},
    {"name": "Marcelo Vieira", "insta_follower_count": 68000000, "description": "Professional Footballer", "country": "Brazil"},
    {"name": "Sergio Ramos", "insta_follower_count": 67000000, "description": "Professional Footballer", "country": "Spain"},
    {"name": "Akshay Kumar", "insta_follower_count": 66000000, "description": "Actor", "country": "India"},
    {"name": "Mohamed Salah", "insta_follower_count": 66000000, "description": "Professional Footballer", "country": "Egypt"},
    {"name": "Paul Pogba", "insta_follower_count": 64000000, "description": "Professional Footballer", "country": "France"},
    {"name": "Zlatan Ibrahimović", "insta_follower_count": 64000000, "description": "Former Professional Footballer", "country": "Sweden"},
    {"name": "Bella Hadid", "insta_follower_count": 61000000, "description": "Model", "country": "United States"},
    {"name": "Tom Holland", "insta_follower_count": 60000000, "description": "Actor", "country": "United Kingdom"},
    {"name": "Camila Cabello", "insta_follower_count": 59000000, "description": "Musician", "country": "Cuba"},
    {"name": "Huda Kattan", "insta_follower_count": 57000000, "description": "Entrepreneur", "country": "United States"},
    {"name": "Maluma", "insta_follower_count": 57000000, "description": "Musician", "country": "Colombia"},
    {"name": "Chris Hemsworth", "insta_follower_count": 56000000, "description": "Actor", "country": "Australia"},
    {"name": "James Rodriguez", "insta_follower_count": 55000000, "description": "Professional Footballer", "country": "Colombia"},
    {"name": "Paulo Dybala", "insta_follower_count": 54000000, "description": "Professional Footballer", "country": "Argentina"},
    {"name": "Lele Pons", "insta_follower_count": 53000000, "description": "Internet Celebrity", "country": "Venezuela"},
    {"name": "Gareth Bale", "insta_follower_count": 52000000, "description": "Former Professional Footballer", "country": "United Kingdom"},
    {"name": "Nusr-et", "insta_follower_count": 51000000, "description": "Chef", "country": "Turkey"},
    {"name": "Robert Downey Jr.", "insta_follower_count": 51000000, "description": "Actor", "country": "United States"},
    {"name": "J Balvin", "insta_follower_count": 50000000, "description": "Musician", "country": "Colombia"},
    {"name": "Conor McGregor", "insta_follower_count": 47000000, "description": "Mixed Martial Artist", "country": "Ireland"},
    {"name": "Luis Suarez", "insta_follower_count": 46000000, "description": "Professional Footballer", "country": "Uruguay"},
    {"name": "Michelle Obama", "insta_follower_count": 45000000, "description": "Author and Former First Lady", "country": "United States"},
    {"name": "Adele", "insta_follower_count": 45000000, "description": "Musician", "country": "United Kingdom"},
    {"name": "Lady Gaga", "insta_follower_count": 45000000, "description": "Musician and Actress", "country": "United States"},
    {"name": "Zac Efron", "insta_follower_count": 44000000, "description": "Actor", "country": "United States"},
    {"name": "Vanessa Hudgens", "insta_follower_count": 43000000, "description": "Actress", "country": "United States"},
    {"name": "Gwyneth Paltrow", "insta_follower_count": 42000000, "description": "Actress and Businesswoman", "country": "United States"},
    {"name": "Charli D'Amelio", "insta_follower_count": 41000000, "description": "Social Media Personality", "country": "United States"},
    {"name": "Olivia Rodrigo", "insta_follower_count": 39000000, "description": "Musician and Actress", "country": "United States"},
    {"name": "Jason Statham", "insta_follower_count": 38000000, "description": "Actor", "country": "United Kingdom"},
    {"name": "Addison Rae", "insta_follower_count": 34000000, "description": "Social Media Personality", "country": "United States"},
    {"name": "Luisito Comunica", "insta_follower_count": 33000000, "description": "YouTuber", "country": "Mexico"},
    {"name": "Zach King", "insta_follower_count": 29000000, "description": "Filmmaker and Illusionist", "country": "United States"},
    {"name": "Chiara Ferragni", "insta_follower_count": 27000000, "description": "Fashion Influencer", "country": "Italy"},
    {"name": "Gordon Ramsay", "insta_follower_count": 17000000, "description": "Chef", "country": "United Kingdom"},
    {"name": "Burak Özdemir", "insta_follower_count": 53000000, "description": "Chef", "country": "Turkey"}
]